### ISSUE TITLE
Planar map topology is coded but not tested yet

### ISSUE THREAD

**Issue by rafaelgioria** [InTRA-USP/IntraSOM#16]
This issue aims to keep a register for the necessity of tests in planar map topology.

OBS: we thank users for contacting us and raising this issue.

**Comment by rodiegeology** [comment]
Planar topology for hexagonal lattice is implemented and tested on release 1.0.1 https://github.com/InTRA-USP/IntraSOM/releases/tag/1.0.1 and already uploaded to PyPi to be installed via pip command. We are opened to any issues with the new implementation. Thanks.
