### ISSUE TITLE
Add tag open in colab in README.md in examples folder (e pasta exemplos)

### ISSUE THREAD

**Issue by rafaelgioria** [InTRA-USP/IntraSOM#3]
README.md in

folders en
https://github.com/InTRA-USP/IntraSOM/tree/english/examples

pasta pt-br
https://github.com/InTRA-USP/IntraSOM/tree/pt_br/exemplos

**Comment by rodiegeology** [comment]
Added to both README files on the created "Open on Google Colab" section.

**Comment by rafaelgioria** [comment]
[PR#5](https://github.com/InTRA-USP/IntraSOM/pull/5) has a modified notebook to be runnable out of the box in colab.

**Comment by rafaelgioria** [comment]
Closed.

Merged in [english](https://github.com/InTRA-USP/IntraSOM/tree/english) branch.
