### ISSUE TITLE
Erro com dados completos e flag 'missing=True'

### ISSUE THREAD

**Issue by rafaelgioria** [InTRA-USP/IntraSOM#7]
Este problema foi identificado numa tentativa de replicar e trabalhar a issue [#6](https://github.com/InTRA-USP/IntraSOM/issues/6) rodando em Colab.

![Screenshot_20230825-193536873_1.jpg](https://github.com/InTRA-USP/IntraSOM/assets/57018894/d2c6e4b5-5347-4dbd-ab6d-87bb95634c48)

```
Starting Training...
Rough Training:
/usr/local/lib/python3.10/dist-packages/intrasom/codebook.py:56: RuntimeWarning: All-NaN slice encountered
  mn = np.tile(np.nanmin(data, axis=0), (self.nnodes, 1))
/usr/local/lib/python3.10/dist-packages/intrasom/codebook.py:57: RuntimeWarning: All-NaN slice encountered
  mx = np.tile(np.nanmax(data, axis=0), (self.nnodes, 1))
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-3464eb92aff6> in <cell line: 1>()
----> 1 som_test.train(train_len_factor=2,
      2                previous_epoch = False)


2 frames
/usr/local/lib/python3.10/dist-packages/intrasom/intrasom.py in train(self, bootstrap, bootstrap_proportion, n_job, save, summary, dtypes, shared_memory, train_rough_len, train_rough_radiusin, train_rough_radiusfin, train_finetune_len, train_finetune_radiusin, train_finetune_radiusfin, train_len_factor, maxtrainlen, history_plot, previous_epoch)
    890             print("Rough Training:")
    891             self.actual_train = "Rough"
--> 892             self.rough_train(njob=n_job,
    893                              shared_memory=shared_memory,
    894                              trainlen=train_rough_len,

/usr/local/lib/python3.10/dist-packages/intrasom/intrasom.py in rough_train(self, njob, shared_memory, trainlen, radiusin, radiusfin, train_len_factor, maxtrainlen)
   1023         self.train_rough_radiusfin = round(radiusfin,2)
   1024 
-> 1025         self._batchtrain(trainlen, radiusin, radiusfin, njob, shared_memory)
   1026 
   1027     def finetune_train(self,

/usr/local/lib/python3.10/dist-packages/intrasom/intrasom.py in _batchtrain(self, trainlen, radiusin, radiusfin, njob, shared_memory)
   1390 
   1391                         # Delete the data in the data variable
-> 1392                         data[self.data_missing["indices"]] = np.full(len(self.data_missing["indices"][0]), np.nan)
   1393                         if self.save_nan_hist:
   1394                             # Add to nan's processing history

IndexError: tuple index out of range
```

> Oi @akol67 
> 
> Obrigado por apontar os erros e dificuldades. 
> 
> Consegui reproduzir o erro nas seguintes condições:
> - dados de entrada completos qualquer dimensão
> - flag erroneamente apontando a existência de missing data `missing=True`
> 
> O nosso notebook tutorial usa um exemplo com missing data, e o setup tem o flag True.
> 
> Se por acaso você aproveitou o notebook exemplo como guia, pode ter ocorrido de manter a flag `missing=True` por engano. É o que o @rodiegeology indicou em [msg](https://github.com/InTRA-USP/IntraSOM/issues/6#issuecomment-1693910726).
> 
> 
> Você poderia verificar?
> 
> _Originalmente postado por @rafaelgioria em https://github.com/InTRA-USP/IntraSOM/issues/6#issuecomment-1694035895_

**Comment by akol67** [comment]
@rafaelgioria O erro com dados completos (o de 20000 linhas) permanece. O ipykernel voa.

![image](https://github.com/InTRA-USP/IntraSOM/assets/37145594/6f79acaa-9d4e-4047-bbf5-c6d59db84a68)

**Comment by rodiegeology** [comment]
I've corrected the quantization error bug as discussed in #6 and updated the calculation of the topographic error, which was not considering a wrap-around neighborhood of the toroidal topology, changes on commit fe5100c. I've run a 20000 samples with 6 features and had no problem. If this change doesn't help with the dying kernel, let me know. A question: are you using a local kernel or google colab?

**Comment by akol67** [comment]
Using a remote kernel, a VDI machine.

**Comment by rafaelgioria** [comment]
@rodiegeology 

I tested:
- completa data was used for training and the flag `missing=False`. it worked fine!
- completa data was used for training and the flag wrongly set `missing=True`. It warned about no missing data found and stoped correctly.

I think we may close this issue.


@rodiegeology and @akol67 
About the dying Kernel: what about to open it is a different issue.
I could not replciate the dying kernel error, yet we shall address this.
