### ISSUE TITLE
NaN in q-error for every sample and warning in bmu_dist calculation in training

### ISSUE THREAD

**Issue by rafaelgioria** [InTRA-USP/IntraSOM#8]
The Training with complete data keeps throwing a warning.

```
Starting Training...
Rough Training:
Fine Tuning:
Saving...
Training Report Created
Training completed successfully.
/usr/local/lib/python3.10/dist-packages/intrasom/intrasom.py:401: RuntimeWarning: invalid value encountered in sqrt
  dic["bmus_dist"] = np.sqrt(self._bmu[1] + fixed_euclidean_x2).tolist()
```
Map size was (24,14) and randomly generated data:

```
import string
nsamp = 9739
nfeat = 9
data = pd.DataFrame( np.random.default_rng().uniform(low=0,high=1,size=[nsamp,nfeat])
, columns=list(string.ascii_lowercase[:nfeat]),)
```

After saving and reading it back, following tutorial notebook,  `som_test.results_dataframe` indicates NaN in q-error for all samples.

**Comment by rafaelgioria** [comment]
Sorry.
Probably I have mixed two issues in this one.

1. Tha NaN in q-error seems like a read/write problem.
2. The runtime warning is still open (I did not take look at it yet).

**Comment by akol67** [comment]
Same RuntimeWarning error to me with my small data. However when using the whole data the kernel crashed and finished working

**Comment by rodiegeology** [comment]
Thanks for the heads up, I'll look into it asap and return.

**Comment by rafaelgioria** [comment]
Runtime error is indeed in the saving process.

If one uses `save = False`, it does not happen.
```
som_test.train(train_len_factor=2,
                 previous_epoch = False,
                 save = False,
                 )
```

**Comment by rafaelgioria** [comment]
I have no fix for it yet but I have noticed that there is a `np.abs` in quantization_error functions and some other places where the calculations is similar (examples in branch [english](/InTRA-USP/IntraSOM/tree/english/): [here L1871](https://github.com/InTRA-USP/IntraSOM/blob/0986e0afb2d5f3b8d03a0d9849d151ccdb4ac4b7/intrasom/intrasom.py#L1871) and [here  L1878](https://github.com/InTRA-USP/IntraSOM/blob/0986e0afb2d5f3b8d03a0d9849d151ccdb4ac4b7/intrasom/intrasom.py#L1878))

I.e.: Would a change from `np.sqrt(self._bmu[1] + fixed_euclidean_x2).tolist()` to `np.sqrt(np.abs(self._bmu[1] + fixed_euclidean_x2)).tolist()` fix it properly?

**Comment by rodiegeology** [comment]
I've corrected the bug with the quantization error and topographic error calculation at the end of the training on commit fe5100c, as discussed on Issue #6. See if it works and let me know. Thanks.

**Comment by akol67** [comment]
Please add some instruction about github update on IntraSOM page.

I did my research and found that all it takes is a git pull, but it
would be better for every user to stay on the install page


Em ter., 29 de ago. de 2023 às 20:08, rodiegeology ***@***.***>
escreveu:

**Comment by rafaelgioria** [comment]
> I've corrected the bug with the quantization error and topographic error calculation at the end of the training on commit [fe5100c](https://github.com/InTRA-USP/IntraSOM/commit/fe5100c12f7c1518ad5753966be6460cc7200ce3), as discussed on Issue #6. See if it works and let me know. Thanks.

No undue warnings here. Good job.
Also there is no more NaN in q-error from loaded trainde SOM maps.

Thanks, @rodiegeology.
I think we may close thiis one too.
